### ISSUE TITLE
Unique constraint - feature suggestion - update instead of insert

### ISSUE THREAD

**Issue by royharoush** [argp/nmapdb#3]
Hi, 
This tools is very useful.
There's a problem when trying to update a database with new results, as i guess the the script uses insert, and it fails on Unique constraint.

Would be great if there was a feature that updates a an existing database instead of trying to insert to it. 
Thanks ! 
Roy

**Comment by mainframed** [comment]
I created a fork (and a pull request) to fix this: https://github.com/mainframed/nmapdb
